# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: nodeapplication

stages:
- stage: AppBuild
  displayName: "Build and Package App"
  jobs:
  - job: Build_the_app
    pool:
      name: azure
    steps:
    - script: |
        npm ci
      displayName: "Install dependencies"
    - script: |
        npm pack
        mv *.tgz $(Build.ArtifactStagingDirectory)/app.tgz
      displayName: "Packaging the app"
    - publish: $(Build.ArtifactStagingDirectory)/app.tgz
      artifact: app-package
      displayName: "Publish app.tgz"
- stage: DockerImageBuild
  displayName: Build image
  dependsOn: AppBuild
  jobs:
  - job: Docker_Image
    displayName: "Build Docker Image"
    pool:
      name: azure
    steps:
    - download: current
      artifact: app-package
      displayName: "Download app artifact"
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Pipeline.Workspace)/app-package'
        repository: $(imageName)
        tags: $(tag)
